name: Weekly Tests

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: ['main']

jobs:
  run-books:
    name: 'get monthly books'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          uv add requests polars
      - run: uv run get-data.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/fable.parquet
          git commit -m "Update books"
          git push